[cell-locator] Fix Ubuntu 20.04 link error updating Python from 2.7.13 to 2.7.15
This commit fixes the following link error:

  /usr/bin/ld: ../../lib/libpython2.7.so: undefined reference to `minor'
  /usr/bin/ld: ../../lib/libpython2.7.so: undefined reference to `major'
  /usr/bin/ld: ../../lib/libpython2.7.so: undefined reference to `makedev'

Fixes https://github.com/BICCN/cell-locator/issues/125


List of changes:

$ git shortlog c3b8d53..a1ce7c2 --no-merges
Anonymous Maarten (1):
      Allow building cpython as a subproject

Arves100 (1):
      Enabled use of MSVC 1900 patches for VS2017+ compilers

David Brooks (4):
      Python 3.6 provides `_blake2` and `_sha3` modules for `hashlib`.
      Add md5 checksums for recent Python 3.6 releases.
      cmake: Fix build of DLL stub library on  Windows with Ninja
      cmake: Tweak name of "python3 stub def" target.

Eric Mehl (1):
      Add support for Python 2.7.15

Jean-Christophe Fillion-Robin (5):
      cmake: Disable weak linking to "fix Symbol not found: _clock_gettime"
      Add support for building _distutils_findvs module introduced in Python 3.6
      appveyor: Update Python from 3.6.4 to 3.6.5 to fix findvs module link error
      README: Improve build instructions [ci skip]
      README: Update default version of Python built by default [ci skip]

John Lund (1):
      cmake: Fix build of iomodule.c for python 3.6.x using VS >= 2017

Rafael Palomar (1):
      cmake: Support building nis module on system having libtirpc

Rob G (1):
      DIRECTORY not available in CMake <=2.8.11. PATH should be used instead